### ISSUE TITLE
ローカルでは動作するがheroku上で動作しない

### ISSUE THREAD

**Issue by shts** [shts/nogi_tweet_observer#1]
ローカルで動作確認後、Herokuにデプロイしたが正しく動作しない。`heroku logs`コマンドでログを見たところ下記ログが出力されていた。

```
2015-02-21T09:50:47.443193+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T09:50:47.425787+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T09:50:49.806923+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T09:50:50.414194+00:00 heroku[observer.1]: State changed from starting to up
2015-02-21T10:01:22.966632+00:00 app[observer.1]: /app/vendor/bundle/ruby/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
2015-02-21T10:01:22.966647+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
2015-02-21T10:01:22.966648+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
2015-02-21T10:01:22.966650+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
2015-02-21T10:01:22.966657+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
2015-02-21T10:01:22.966652+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
2015-02-21T10:01:22.966656+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
2015-02-21T10:01:22.966660+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
2015-02-21T10:01:22.966658+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
2015-02-21T10:01:22.966661+00:00 app[observer.1]:   from observer.rb:42:in `<main>'
2015-02-21T10:01:23.652772+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T10:01:23.651780+00:00 heroku[observer.1]: State changed from up to crashed
2015-02-21T10:01:23.640472+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T10:01:27.389154+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T10:01:27.935639+00:00 heroku[observer.1]: State changed from starting to up
2015-02-21T10:12:00.999318+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
2015-02-21T10:12:00.999293+00:00 app[observer.1]: /app/vendor/bundle/ruby/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
2015-02-21T10:12:00.999308+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
2015-02-21T10:12:00.999310+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
2015-02-21T10:12:00.999307+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
2015-02-21T10:12:00.999315+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
2015-02-21T10:12:00.999316+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
2015-02-21T10:12:00.999321+00:00 app[observer.1]:   from observer.rb:42:in `<main>'
2015-02-21T10:12:00.999311+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
2015-02-21T10:12:00.999319+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
2015-02-21T10:12:01.772823+00:00 heroku[observer.1]: State changed from up to crashed
2015-02-21T10:12:01.759937+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T10:24:04.082886+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T10:24:06.460188+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T10:24:07.097034+00:00 heroku[observer.1]: State changed from starting to up
2015-02-21T10:34:39.290915+00:00 app[observer.1]: /app/vendor/bundle/ruby/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
2015-02-21T10:34:39.290932+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
2015-02-21T10:34:39.290930+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
2015-02-21T10:34:39.290934+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
2015-02-21T10:34:39.290939+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
2015-02-21T10:34:39.290941+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
2015-02-21T10:34:39.290942+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
2015-02-21T10:34:39.290944+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
2015-02-21T10:34:39.290945+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
2015-02-21T10:34:39.290947+00:00 app[observer.1]:   from observer.rb:42:in `<main>'
2015-02-21T10:34:39.989332+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T10:34:40.001200+00:00 heroku[observer.1]: State changed from up to crashed
2015-02-21T10:34:40.002201+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T10:34:41.894085+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T10:34:42.500343+00:00 heroku[observer.1]: State changed from starting to up
2015-02-21T10:45:14.688326+00:00 app[observer.1]: /app/vendor/bundle/ruby/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
2015-02-21T10:45:14.688343+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
2015-02-21T10:45:14.688345+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
2015-02-21T10:45:14.688347+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
2015-02-21T10:45:14.688349+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
2015-02-21T10:45:14.688354+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
2015-02-21T10:45:14.688355+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
2015-02-21T10:45:14.688357+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
2015-02-21T10:45:14.688359+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
2015-02-21T10:45:14.688360+00:00 app[observer.1]:   from observer.rb:42:in `<main>'
2015-02-21T10:45:15.418558+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T10:45:15.437312+00:00 heroku[observer.1]: State changed from up to crashed
2015-02-21T10:48:21.877029+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T10:48:23.621564+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T10:48:24.181573+00:00 heroku[observer.1]: State changed from starting to up
2015-02-21T10:58:55.922993+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
2015-02-21T10:58:55.922978+00:00 app[observer.1]: /app/vendor/bundle/ruby/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
2015-02-21T10:58:55.922995+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
2015-02-21T10:58:55.922998+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
2015-02-21T10:58:55.923003+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
2015-02-21T10:58:55.922997+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
2015-02-21T10:58:55.923005+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
2015-02-21T10:58:55.923006+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
2015-02-21T10:58:55.923008+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
2015-02-21T10:58:55.923010+00:00 app[observer.1]:   from observer.rb:42:in `<main>'
2015-02-21T10:58:56.570987+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T10:58:56.585390+00:00 heroku[observer.1]: State changed from up to crashed
2015-02-21T11:00:49.567647+00:00 heroku[api]: Starting process with command `ruby -e "puts RUBY_VERSION"` by shts.dev@gmail.com
2015-02-21T11:00:52.345047+00:00 heroku[run.7642]: Awaiting client
2015-02-21T11:00:52.385153+00:00 heroku[run.7642]: Starting process with command `ruby -e "puts RUBY_VERSION"`
2015-02-21T11:00:52.671760+00:00 heroku[run.7642]: State changed from starting to up
2015-02-21T11:00:54.670456+00:00 heroku[run.7642]: Process exited with status 0
2015-02-21T11:00:54.681451+00:00 heroku[run.7642]: State changed from up to complete
2015-02-21T11:04:46.496218+00:00 heroku[api]: Scale to observer=1 by shts.dev@gmail.com
2015-02-21T11:07:57.399491+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T11:07:59.317720+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T11:07:59.884989+00:00 heroku[observer.1]: State changed from starting to up
2015-02-21T11:18:32.321294+00:00 app[observer.1]: /app/vendor/bundle/ruby/2.0.0/gems/tweetstream-2.6.1/lib/tweetstream/client.rb:449:in `block in connect': Failed to reconnect after 6 tries. (TweetStream::ReconnectError)
2015-02-21T11:18:32.321310+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `call'
2015-02-21T11:18:32.321312+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:297:in `invoke_callback'
2015-02-21T11:18:32.321316+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:269:in `rescue in schedule_reconnect'
2015-02-21T11:18:32.321318+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:264:in `schedule_reconnect'
2015-02-21T11:18:32.321320+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/em-twitter-0.3.5/lib/em-twitter/connection.rb:92:in `unbind'
2015-02-21T11:18:32.321322+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:1457:in `event_callback'
2015-02-21T11:18:32.321323+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
2015-02-21T11:18:32.321325+00:00 app[observer.1]:   from /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
2015-02-21T11:18:32.321327+00:00 app[observer.1]:   from observer.rb:42:in `<main>'
2015-02-21T11:18:33.051890+00:00 heroku[observer.1]: State changed from up to crashed
2015-02-21T11:18:33.035858+00:00 heroku[observer.1]: Process exited with status 1
2015-02-21T11:27:26.681867+00:00 heroku[observer.1]: State changed from crashed to starting
2015-02-21T11:27:28.792308+00:00 heroku[observer.1]: Starting process with command `bundle exec ruby observer.rb`
2015-02-21T11:27:29.442962+00:00 heroku[observer.1]: State changed from starting to up

```

**Comment by shts** [comment]
環境変数の設定方法に誤りがあった。環境変数を.envファイルに記載し`git push heroku master`でherokuリポジトリにpushすれば勝手に設定されると勘違いしていた。
`git config`コマンドから設定することで期待動作を確認できた。
